### ISSUE TITLE
Latest Python 3 Compat Change Broke my output

### ISSUE THREAD

**Issue by jusrob** [DataDog/datadogpy#275]
Change https://github.com/DataDog/datadogpy/commit/b55a4c85b4faf8e3aa8e8f24a20a2c8538b0881f broke dogwrap logging on our systems.

Exception in thread Thread-1:
Traceback (most recent call last):
   File "/usr/lib64/python2.7/threading.py", line 804, in __bootstrap_inner
     self.run()
   File "/usr/local/lib/python2.7/site-packages/datadog/dogshell/wrap.py", line 68, in run
     print >> sys.stderr, self._fwd_out.encode('utf8')
 AttributeError: 'file' object has no attribute 'encode'

**Comment by jusrob** [comment]
I would think that changing line 67 to ` if self._fwd_out.encoding is not None:` would address it.

**Comment by zippolyte** [comment]
Hey @jusrob 

I believe #379 should fix your issues.

Closing, feel free to reopen if that's not the case.
