### ISSUE TITLE
ERROR:datadog.threadstats:Error flushing metrics and events

### ISSUE THREAD

**Issue by athap** [DataDog/datadogpy#285]
```
ERROR:datadog.threadstats:Error flushing metrics and events
Traceback (most recent call last):
  File "/opt/dogweb/lib/python2.7/site-packages/datadog/threadstats/base.py", line 294, in flush
    self.reporter.flush_metrics(metrics)
  File "/opt/dogweb/lib/python2.7/site-packages/datadog/threadstats/reporters.py", line 18, in flush_metrics
    api.Metric.send(metrics)
  File "/opt/dogweb/lib/python2.7/site-packages/datadog/api/metrics.py", line 140, in send
    return super(Metric, cls).send(attach_host_name=True, **metrics_dict)
  File "/opt/dogweb/lib/python2.7/site-packages/datadog/api/resources.py", line 74, in send
    attach_host_name=attach_host_name)
  File "/opt/dogweb/lib/python2.7/site-packages/datadog/api/api_client.py", line 129, in submit
    proxies=_proxies, verify=_cacert
  File "/opt/dogweb/lib/python2.7/site-packages/datadog/api/http_client.py", line 71, in request
    proxies=proxies, verify=verify)
  File "/opt/dogweb/lib/python2.7/site-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/opt/dogweb/lib/python2.7/site-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/opt/dogweb/lib/python2.7/site-packages/requests/adapters.py", line 440, in send
    timeout=timeout
  File "/opt/dogweb/lib/python2.7/site-packages/urllib3/connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "/opt/dogweb/lib/python2.7/site-packages/urllib3/connectionpool.py", line 346, in _make_request
    self._validate_conn(conn)
  File "/opt/dogweb/lib/python2.7/site-packages/urllib3/connectionpool.py", line 850, in _validate_conn
    conn.connect()
  File "/opt/dogweb/lib/python2.7/site-packages/urllib3/connection.py", line 326, in connect
    ssl_context=context)
  File "/opt/dogweb/lib/python2.7/site-packages/urllib3/util/ssl_.py", line 329, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "/opt/dogweb/lib/python2.7/site-packages/urllib3/contrib/pyopenssl.py", line 443, in wrap_socket
    rd = util.wait_for_read(sock, sock.gettimeout())
  File "/opt/dogweb/lib/python2.7/site-packages/urllib3/util/wait.py", line 33, in wait_for_read
    return _wait_for_io_events(socks, EVENT_READ, timeout)
  File "/opt/dogweb/lib/python2.7/site-packages/urllib3/util/wait.py", line 22, in _wait_for_io_events
    with DefaultSelector() as selector:
  File "/opt/dogweb/lib/python2.7/site-packages/urllib3/util/selectors.py", line 581, in DefaultSelector
    return _DEFAULT_SELECTOR()
  File "/opt/dogweb/lib/python2.7/site-packages/urllib3/util/selectors.py", line 394, in __init__
    self._epoll = select.epoll()
AttributeError: 'module' object has no attribute 'epoll'
```

**Comment by athap** [comment]
This looks like it is related to gevent?

**Comment by zippolyte** [comment]
Hello @athap,

It looks indeed like this could be related to `gevent`, and its monkey patching. It looks similar to this issue https://github.com/kennethreitz/requests/issues/3831.

Where are you monkey_patch `gevent` in your code ? Looks like it has to be done before importing anything, and not right before starting ThreadStats as currently stated here: https://github.com/DataDog/datadogpy/blob/b829d13f3f81cc9c92661a1cddf324aaba9f75c8/datadog/threadstats/base.py#L61-L66.

Does this help ?
Sorry for the lack of responses before today.

**Comment by zippolyte** [comment]
Hi @athap,

Moving the location where you monkey patch gevent should solve the problem. 
Closing this issue, but feel free to reopen if that is not the case.
