### ISSUE TITLE
api.Monitor.search() returns "400 malformed request" html

### ISSUE THREAD

**Issue by alexandru-gaina** [DataDog/datadogpy#375]
Any call to _api.Monitor.search()_ with parameters or without returns a 400 status code as response. For this call the request body is an empty JSON object('{}') rather than being _None_ (as for other 'GET' requests) and the headers accordingly contain _'Content-Type': 'application/json'_

**Comment by zippolyte** [comment]
Hello @alexandru-gaina,

The following script works perfectly fine for me. Can you provide more details into how you are encountering the issue ?

```python
from datadog import initialize, api

options = {
    "api_key": *******,
    "app_key": *******
}
initialize(**options)

print(api.Monitor.search(query="title:foo metric:system.core.idle status:Alert"))
print(api.Monitor.search())
```

**Comment by alexandru-gaina** [comment]
Using python 3.7.3 and datadogpy 0.28.0.
My code looks like this:

```
import os
from datadog import initialize, api

datadog_api_key = os.getenv("DATADOG_API_KEY")
datadog_app_key = os.getenv("DATADOG_APP_KEY")
datadog_host = os.getenv("DATADOG_HOST")

options = {
    'api_key': datadog_api_key,
    'app_key': datadog_app_key,
    'api_host': datadog_host,
}

initialize(**options)

triggered_monitors = api.Monitor.search(
    query='status:(Alert OR Warn)'
)
# OR triggered_monitors = api.Monitor.search()
```
Any of the two _api.Monitor.search()_ calls returns an HTML response which causes this python error:
```
Traceback (most recent call last):
  File "/home/myscript.py", line 22, in <module>
    triggered_monitors = api.Monitor.search()
  File "/usr/lib/python3.7/site-packages/datadog/api/monitors.py", line 115, in search
    return super(Monitor, cls)._trigger_class_action('GET', 'search', params=params)
  File "/usr/lib/python3.7/site-packages/datadog/api/resources.py", line 341, in _trigger_class_action
    return APIClient.submit(method, path, body, **params)
  File "/usr/lib/python3.7/site-packages/datadog/api/api_client.py", line 148, in submit
    raise ValueError('Invalid JSON response: {0}'.format(content))
ValueError: Invalid JSON response: b'<!DOCTYPE html>\n<html lang=en>\n  <meta charset=utf-8>\n
<meta name=viewport content="initial-scale=1, minimum-scale=1, width=device-width">\n
<title>Error 400 (Bad Request)!!1</title>\n
...
<p><b>400.</b> <ins>That\xe2\x80\x99s an error.</ins>\n  <p>Your client has issued a malformed or illegal request.
<ins>That\xe2\x80\x99s all we know.</ins>\n'
```

**Comment by zippolyte** [comment]
Thanks for the additional information. 
With the datadoghq.eu host, I get the same error as you ! I'll look into that !
