### ISSUE TITLE
api_client.py imports non-existent field from api

### ISSUE THREAD

**Issue by rodneykinney** [DataDog/datadogpy#460]
In version 0.30, this error is thrown when trying to flush metrics from a `threadstats` recorder:

```
Traceback (most recent call last):
  File "/worker/python/lib/python3.7/site-packages/datadog/threadstats/base.py", line 312, in flush
    self.reporter.flush_metrics(metrics)
  File "/worker/python/lib/python3.7/site-packages/datadog/threadstats/reporters.py", line 21, in flush_metrics
    api.Metric.send(metrics)
  File "/worker/python/lib/python3.7/site-packages/datadog/api/metrics.py", line 91, in send
    return super(Metric, cls).send(attach_host_name=attach_host_name, **metrics_dict)
  File "/worker/python/lib/python3.7/site-packages/datadog/api/resources.py", line 78, in send
    attach_host_name=attach_host_name)
  File "/worker/python/lib/python3.7/site-packages/datadog/api/api_client.py", line 84, in submit
    from datadog.api import _api_key, _application_key, _api_host, \
ImportError: cannot import name '_return_raw_response' from 'datadog.api' (/worker/python/lib/python3.7/site-packages/datadog/api/__init__.py)
```

It looks as though every field referenced in [this import](https://github.com/DataDog/datadogpy/blob/v0.30.0/datadog/api/api_client.py#L86) can be found in the [api module](https://github.com/DataDog/datadogpy/blob/v0.30.0/datadog/api/__init__.py) except for `_return_raw_response`.

**Comment by rodneykinney** [comment]
Thanks for the response. It looks like failing to initialize was the problem.
