### ISSUE TITLE
forbidden by administrative rules error

### ISSUE THREAD

**Issue by sudhishkasabaramesh** [DataDog/datadogpy#499]
```
Traceback (most recent call last):
  File "/metering/src/metering.py", line 54, in <module>
    main()
  File "/metering/src/metering.py", line 50, in main
    args.func(args)
  File "/metering/src/metering.py", line 31, in databases
    tags=tags_obj.datadog_tags()
  File "/home/z-pyenv/pyenv/versions/3.6/lib/python3.6/site-packages/datadog/api/metrics.py", line 106, in send
    attach_host_name=attach_host_name, compress_payload=compress_payload, **metrics_dict
  File "/home/z-pyenv/pyenv/versions/3.6/lib/python3.6/site-packages/datadog/api/resources.py", line 85, in send
    compress_payload=compress_payload
  File "/home/z-pyenv/pyenv/versions/3.6/lib/python3.6/site-packages/datadog/api/api_client.py", line 179, in submit
    raise ValueError('Invalid JSON response: {0}'.format(content))
ValueError: Invalid JSON response: b'<html><body><h1>403 Forbidden</h1>\nRequest forbidden by administrative rules.\n</body></html>\n'
```

I having this intermittent errors with datadog. This seems to have started since dec'12th. Upon looking I noticed a new release was out on dec'12th. And I was not pinning the package.

Looking for help to debug this.

**Comment by dabcoder** [comment]
@sudhishkasabaramesh Can you reach out to support@datadoghq.com with the version of datadogpy that you are currently using and with which you can see this error as well as any additional details (if you have any) and we'll follow up with you? Thanks.
