### ISSUE TITLE
Getting "Error flushing metrics and events" when using Flask API with DD

### ISSUE THREAD

**Issue by ariel-linearb** [DataDog/datadogpy#626]
**Describe the bug**
Getting this error when using python Flask API

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/datadog/api/api_client.py", line 180, in submit
    response_obj = json.loads(content.decode('utf-8'))
  File "/usr/local/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/datadog/threadstats/base.py", line 335, in flush
    self.reporter.flush_metrics(metrics)
  File "/usr/local/lib/python3.7/site-packages/datadog/threadstats/reporters.py", line 27, in flush_metrics
    api.Metric.send(metrics, compress_payload=self.compress_payload)
  File "/usr/local/lib/python3.7/site-packages/datadog/api/metrics.py", line 109, in send
    attach_host_name=attach_host_name, compress_payload=compress_payload, **metrics_dict
  File "/usr/local/lib/python3.7/site-packages/datadog/api/resources.py", line 88, in send
    compress_payload=compress_payload
  File "/usr/local/lib/python3.7/site-packages/datadog/api/api_client.py", line 184, in submit
    raise ValueError('Invalid JSON response: {0}'.format(content))
ValueError: Invalid JSON response: b'Payload is not in the expected format: json: cannot unmarshal number into Go struct field MetricPayload.series of type string'
```

**Expected behavior**

**Screenshots**

**Environment and Versions (please complete the following information):**
Using the latest datadog module 0.39.0

**Additional context**
N/A

**Comment by therve** [comment]
Hi, can you give the payload that you send? Thanks.

**Comment by ariel-linearb** [comment]
what do you mean by payload, i mean i consume the package like this

```
from datadog import initialize, ThreadStats

options = {
    'api_key': api_key,
    'app_key': environ.get('DD_APP_KEY'),
    'statsd_host': environ.get('DD_STATSD_HOST'),
    'statsd_port': environ.get('DD_STATSD_PORT'),
}

initialize(**options)

self.client = ThreadStats(namespace='lin.app.{}'.format(self.application))`
self.client.start()


client.timing(get_qualified_metric_name(namespace, metric),
                               value,
                               dict(tag='22222'))
```

**Comment by ariel-linearb** [comment]
@therve hi, can you take a look please ? many thanks

**Comment by therve** [comment]
Sorry missed your message.

I can't really do much with your example. I don't have the `get_qualified_metric_name` function. The call to `timing` is wrong as you pass the tags the timestamp argument. But this fails in datadopgy so I suspect this is not how you actually send data?

**Comment by ariel-linearb** [comment]
yea, it's just an example - the `get_qualified_metric_name` is just an helper function returning some string. Anyway, i wonder if the error related to the fact that i might send tags with integer values, or it's just some setup issue i have with the package in order it will work as expected with flask api. Any suggestion where should i start investigate this further ? thanks

**Comment by therve** [comment]
I looked at the logs on our backend, and yes the issue is that you're submitting integer as tag values (for `org_id`). You're also submitting a dict for the tags, which I'm not sure what it does, but it should be a list of strings.

**Comment by ariel-linearb** [comment]
got it! thank you

**Comment by ariel-linearb** [comment]
@therve hi

I have uploaded a fix on our side that wrap all tags in str(), i.e. 
```
client.increment('metric', tags=dict(organization_id=str(organization_id)))
```

but still i get these errors :
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/datadog/api/api_client.py", line 144, in submit
    response_obj = json.loads(content.decode('utf-8'))
  File "/usr/local/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/datadog/threadstats/base.py", line 312, in flush
    self.reporter.flush_metrics(metrics)
  File "/usr/local/lib/python3.7/site-packages/datadog/threadstats/reporters.py", line 21, in flush_metrics
    api.Metric.send(metrics)
  File "/usr/local/lib/python3.7/site-packages/datadog/api/metrics.py", line 91, in send
    return super(Metric, cls).send(attach_host_name=True, **metrics_dict)
  File "/usr/local/lib/python3.7/site-packages/datadog/api/resources.py", line 74, in send
    attach_host_name=attach_host_name)
  File "/usr/local/lib/python3.7/site-packages/datadog/api/api_client.py", line 148, in submit
    raise ValueError('Invalid JSON response: {0}'.format(content))
ValueError: Invalid JSON response: b'Payload is not in the expected format: json: cannot unmarshal number into Go struct field MetricPayload.series of type string'
```

Any idea ?

Regarding the dict - i've always sent the tags like that and it is working in other places so ....

Thank you.

**Comment by therve** [comment]
@ariel-linearb I'm looking at the traces on the server side, and still seeing integer for that tag. Have you deployed everywhere? If you contact support we can give you details of your requests. Thanks.

**Comment by ariel-linearb** [comment]
yea, i'll contact support. Should i tell them everything i mentioned here ?

**Comment by therve** [comment]
Yes please. You can name me so that I can forward the info quickly.
