### ISSUE TITLE
Caching statsd socket doesn't work for Kubernetes DaemonSet

### ISSUE THREAD

**Issue by mbigras** [DataDog/datadogpy#653]
DogStatsd instances save the UDP sockets in the `self.socket` variable. This works when there is only 1 datadog-agent but when we run the datadog-agent as a Kubernetes DaemonSet then caching the socket doesn't work and leads to dropped packets.

The term "DaemonSet" in a Kubernetes context means the datadog-agent will run on each node (each machine) in the cluster. So there will be multiple datadog-agents. This [How to set up DataDog in Kubernetes with Maestro](https://blog.cloud66.com/how-to-set-up-datadog-in-kubernetes-with-maestro/) Cloud 66 article describes one way to run the datadog-agent as a DaemonSet.

Kubernetes will load-balance packets sent to the datadog-agents so the saved UDP connection won't work when clients send to a datadog-agent container without an established UDP connection.

This example illustrates the idea using the `socket` Python module where there are two datadog-agents load-balanced by Kubernetes:

```
>>> import socket
>>> sock = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
>>> sock.connect(("datadog-agent", 8125))
>>> sock.send("hello world".encode("utf-8"))
11
>>> sock.send("hello world".encode("utf-8"))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ConnectionRefusedError: [Errno 111] Connection refused
>>> sock.send("hello world".encode("utf-8"))
11
>>> sock.send("hello world".encode("utf-8"))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ConnectionRefusedError: [Errno 111] Connection refused
```

In contrast, this example uses a Python context manager and works reliably because the connection is always refreshed:

```
>>> import socket
>>> def hello():
...     with socket.socket(socket.AF_INET, socket.SOCK_DGRAM) as sock:
...         sock.connect(("datadog-agent", 8125))
...         return sock.send("hello world".encode("utf-8"))
...
>>> hello()
11
>>> hello()
11
>>> hello()
11
```

This example illustrates the dropped packets using the `datadog.statsd.increment` function:

```
>>> import datadog
>>> datadog.initialize(statsd_host="datadog-agent",statsd_port=8125)
>>> datadog.statsd.increment(f'maxtest.events.helloworld'); datadog.statsd.packets_dropped
0
>>> datadog.statsd.increment(f'maxtest.events.helloworld'); datadog.statsd.packets_dropped
0
>>> datadog.statsd.increment(f'maxtest.events.helloworld'); datadog.statsd.packets_dropped
1
>>> datadog.statsd.increment(f'maxtest.events.helloworld'); datadog.statsd.packets_dropped
1
>>> datadog.statsd.increment(f'maxtest.events.helloworld'); datadog.statsd.packets_dropped
0
>>> datadog.statsd.increment(f'maxtest.events.helloworld'); datadog.statsd.packets_dropped
1
>>> datadog.statsd.increment(f'maxtest.events.helloworld'); datadog.statsd.packets_dropped
1
```

The problem is in the `_xmit_packet` function:

https://github.com/DataDog/datadogpy/blob/ec571f6593c983c0228fd7b6019bced1c5e7fc93/datadog/dogstatsd/base.py#L629-L635

One quick workaround is to close the socket before checking if the socket is cached:

```
# datadog/dogstatsd/base.py
#...
    def _xmit_packet(self, packet, is_telemetry):
        try:
            if is_telemetry and self._dedicated_telemetry_destination():
                if os.environ.get("REFRESH_SOCKET"):
                        self.close_socket()
                mysocket = self.telemetry_socket or self.get_socket(telemetry=True)
            else:
                if os.environ.get("REFRESH_SOCKET"):
                        self.close_socket()
                # If set, use socket directly
                mysocket = self.socket or self.get_socket()

            mysocket.send(packet.encode(self.encoding))
#...
```

Then the socket is refreshed every time and no packets are dropped:

```
>>> import datadog
>>> import os
>>> os.environ["REFRESH_SOCKET"] = "yes"
>>> datadog.initialize(statsd_host="datadog-agent",statsd_port=8125)
>>> datadog.statsd.increment(f'maxtest.events.helloworld'); datadog.statsd.packets_dropped
0
>>> datadog.statsd.increment(f'maxtest.events.helloworld'); datadog.statsd.packets_dropped
0
>>> datadog.statsd.increment(f'maxtest.events.helloworld'); datadog.statsd.packets_dropped
0
```

There might be a better way to integrate this concept into datadogpy. Also, there might be a different way to solve this problem at the Kubernetes level.

**Expected behavior**
`datadog.statsd.increment` works with a datadog-agent running as a Kubernetes DaemonSet.

**Environment and Versions (please complete the following information):**
datadog==0.41.0

**Comment by sgnn7** [comment]
Hey @mbigras,

Apologies for late reply as sometimes issue notification can easily get missed by the email filters.

This seems like a reasonable request but using the simple approach of just reopening the socket could be problematic. While UDP won't be affected much by binding to the socket since they are stateless (it's not costless though and there may be incidental tech issues),  Unix sockets may run the risk of having severely degraded performance ([rejected kernel patch](https://patchwork.ozlabs.org/project/netdev/patch/1435485139-16866-1-git-send-email-ch@bitfehler.net/)) and this effect would likely be very apparent in high-throughput environments. Either way, some PoCs and benchmarks would probably need to be run to verify the theory before any work begins.

With that said, there's nothing stopping us from having a flag (defaulted to disabled) for closing the socket immediately _but_ this seems like an edge case usage that may not get high enough priority for a patch vs the other high-value changes needed in the short/medium-term plans. We can keep this issue open for now as it's a valid improvement but I probably would expect that this would be a community-contributed change if desired.
