### ISSUE TITLE
Missing : sync flush to send metric without sleep

### ISSUE THREAD

**Issue by raphaelauv** [DataDog/datadogpy#654]
Hello until recently I could use 

```python
statsd.close_buffer()
```
 at the end of my script to be sure that metrics are produce

but with latest version I get an error.

```
[2021-05-28 08:38:20,536] {docker_operator.py:243} INFO - Traceback (most recent call last):
  File "main.py", line 14, in <module>
    statsd.close_buffer()
  File "/usr/local/lib/python3.7/site-packages/datadog/dogstatsd/base.py", line 380, in close_buffer
    raise BufferError("Cannot close buffer that was never opened")
BufferError: Cannot close buffer that was never opened
```

**By reading the documentation I can't find a working example to produce a metric , send it and then close the program without sleep.**

**Comment by raphaelauv** [comment]
By searching I see it's from https://github.com/DataDog/datadogpy/releases/tag/v0.41.0

https://github.com/DataDog/datadogpy/pull/642

https://github.com/DataDog/datadogpy/pull/642#discussion_r606293386

so it's necessary to add a

```
statsd.open_buffer()
```

**Comment by raphaelauv** [comment]
One way is to set telemetry_min_flush_interval at 0

```python
initialize(statsd_host=DD_AGENT_HOST,
           statsd_port=DD_STATSD_PORT,
           statsd_constant_tags=[f"env:{ENV}"],
           telemetry_min_flush_interval=0)
```
