### ISSUE TITLE
Exception in thread Thread-2

### ISSUE THREAD

**Issue by Venkyvemuri** [DataDog/datadogpy#677]
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/threading.py", line 804, in __bootstrap_inner
    self.run()
  File "/usr/local/lib/python2.7/site-packages/mongo_connector-2.5.2.dev0-py2.7.egg/mongo_connector/util.py", line 104, in wrapped
    func(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/mongo_connector-2.5.2.dev0-py2.7.egg/mongo_connector/connector.py", line 347, in run
    self.main_conn.admin.command('buildInfo')['version'])
  File "build/bdist.linux-x86_64/egg/pymongo/database.py", line 513, in command
    with client._socket_for_reads(read_preference) as (sock_info, slave_ok):
  File "/usr/lib64/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "build/bdist.linux-x86_64/egg/pymongo/mongo_client.py", line 904, in _socket_for_reads
    with self._get_socket(read_preference) as sock_info:
  File "/usr/lib64/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "build/bdist.linux-x86_64/egg/pymongo/mongo_client.py", line 868, in _get_socket
    server = self._get_topology().select_server(selector)
  File "build/bdist.linux-x86_64/egg/pymongo/topology.py", line 214, in select_server
    address))
  File "build/bdist.linux-x86_64/egg/pymongo/topology.py", line 189, in select_servers
    self._error_message(selector))

**Comment by therve** [comment]
Hi,

There is no reference to datadogpy in your traceback. Please reopen with more information. Thanks.
