### ISSUE TITLE
SSLError: [Errno 185090050] _ssl.c:344: error:0B084002:x509 certificate routines:X509_load_cert_crl_file:system lib

### ISSUE THREAD

**Issue by glederrey** [DataDog/datadogpy#79]
Hi, 

I'm using dogstatsd on a Windows 7 machine and I always get this error:

    2015-08-20 15:31:58 W. Europe Daylight Time | ERROR | dogstatsd(dogstatsd.pyc:216) | Unable to post payload.
    Traceback (most recent call last):
      File "dogstatsd.pyc", line 206, in submit_http
      File "requests\api.pyc", line 94, in post
      File "requests\api.pyc", line 49, in request
      File "requests\sessions.pyc", line 457, in request
      File "requests\sessions.pyc", line 569, in send
      File "requests\adapters.pyc", line 420, in send
    SSLError: [Errno 185090050] _ssl.c:344: error:0B084002:x509 certificate routines:X509_load_cert_crl_file:system lib

Do you have any idea how to get rid of this error?? 

Thanks in advance

**Comment by yannmh** [comment]
Sorry to hear you have trouble with `dogstatsd` @glederrey. 

The issue you're describing is related to the Datadog agent, especially [`dogstatsd` module](https://github.com/DataDog/dd-agent). 

Would you mind to reach out to support AT datadoghq.com with those details please ? We'll be able to follow up quicker and more efficiently !
